reset; 								# Resetear datos cada corrida
option solver cplex;				# CPLEX resolvera el problema
model svm_inf.mod;					# Cargar modelo (se asume que esta en la misma carpeta)
data sg4.dat;					# Cargar datos 
solve;								# Resolver el problema
print "z:" >> "sg_inf.txt";
print z >> "sg_inf.txt";						# Muestre variables de interes
print "W:" >> "sg_inf.txt";
print {n in atributos} : W[n] >> "sg_inf.txt";
print W_ABS >> "sg_inf.txt";
print CHI >> "sg_inf.txt";
